apiVersion: v1
kind: Service
metadata:
  name: manticore
  namespace: infra-bridges
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: http
      port: 9308
      targetPort: 9308
      protocol: TCP
    - name: mysql
      port: 9306
      targetPort: 9306
      protocol: TCP
