apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: infra-bridges
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
