apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra-bridges
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
